import type {FinalizedVertexShaderMainSpecificationStatements} from "./FinalizedVertexShaderMainSpecificationStatements.ts";
export interface WithFinalAssignmentsVertexShaderMainSpecificationStatements
	extends FinalizedVertexShaderMainSpecificationStatements {}
