import type {FinalizedVertexShaderMainSpecificationStatements} from "./FinalizedVertexShaderMainSpecificationStatements.ts";
export interface WithFinalElseVertexShaderMainSpecificationStatements
	extends FinalizedVertexShaderMainSpecificationStatements {}
