import type {FinalizedVertexShaderSourceCodeMainStatements} from "./FinalizedVertexShaderSourceCodeMainStatements.ts";
export interface WithFinalFinalAssignmentsVertexShaderSourceCodeMainStatements
	extends FinalizedVertexShaderSourceCodeMainStatements {}
