import type {FinalizedFragmentShaderSourceCodeMainStatements} from "./FinalizedFragmentShaderSourceCodeMainStatements.ts";
export interface WithFinalFinalAssignmentsFragmentShaderSourceCodeMainStatements
	extends FinalizedFragmentShaderSourceCodeMainStatements {}
