import type {FinalizedFragmentShaderSourceCodeMainStatements} from "./FinalizedFragmentShaderSourceCodeMainStatements.ts";
export interface WithFinalDiscardFragmentShaderSourceCodeMainStatements
	extends FinalizedFragmentShaderSourceCodeMainStatements {}
