import type {FinalizedCustomFunctionStatements} from "./FinalizedCustomFunctionStatements.ts";
export interface WithFinalFinalAssignmentsFragmentShaderSourceCodeMainStatements
	extends FinalizedCustomFunctionStatements {}
