import type {FinalAssignmentsVertexShaderMainSpecificationStatements} from "./FinalAssignmentsVertexShaderMainSpecificationStatements.ts";
import type {FinalAssignmentVertexShaderMainSpecificationStatements} from "./FinalAssignmentVertexShaderMainSpecificationStatements.ts";
import type {FinalIfVertexShaderMainSpecificationStatements} from "./FinalIfVertexShaderMainSpecificationStatements.ts";
import type {WithFinalAssignmentsVertexShaderMainSpecificationStatements} from "./WithFinalAssignmentsVertexShaderMainSpecificationStatements.ts";
import type {WithFinalIfVertexShaderMainSpecificationStatements} from "./WithFinalIfVertexShaderMainSpecificationStatements.ts";
export interface WithFinalAssignmentVertexShaderMainSpecificationStatements {
	pushIf(
		if_: FinalIfVertexShaderMainSpecificationStatements,
	): WithFinalIfVertexShaderMainSpecificationStatements;
	pushAssignment(
		assignment: FinalAssignmentVertexShaderMainSpecificationStatements,
	): WithFinalAssignmentVertexShaderMainSpecificationStatements;
	pushAssignments(
		assignments: FinalAssignmentsVertexShaderMainSpecificationStatements,
	): WithFinalAssignmentsVertexShaderMainSpecificationStatements;
}
