import type {FinalizedCustomFunctionStatements} from "./FinalizedCustomFunctionStatements.ts";
export interface WithFinalFinalAssignmentsVertexShaderSourceCodeMainStatements
	extends FinalizedCustomFunctionStatements {}
