import type {FinalizedVertexShaderSourceCodeMainStatements} from "./FinalizedVertexShaderSourceCodeMainStatements.ts";
export interface WithFinalElseVertexShaderSourceCodeMainStatements
	extends FinalizedVertexShaderSourceCodeMainStatements {}
