import type {FinalizedFragmentShaderSourceCodeMainStatements} from "./FinalizedFragmentShaderSourceCodeMainStatements.ts";
export interface WithFinalElseFragmentShaderSourceCodeMainStatements
	extends FinalizedFragmentShaderSourceCodeMainStatements {}
