version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
